name = "cdev-meetup/hello_aiken"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'cdev-meetup/hello_aiken'"

[repository]
user = "cdev-meetup"
project = "hello_aiken"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.8.0"
source = "github"

[[dependencies]]
name = "aiken-extra/string_util"
version = "3.180.202403"
source = "github"
